### ISSUE TITLE
[Mod Compat - Crash] Tweaker's Construct and PlusTiC Act Adds Diamatine

### ISSUE THREAD

**Issue by ElvenChaos** [RCXcrafter/TweakersConstruct#1]
When using Tweaker's Construct to edit Act Adds. diamatine _(material added by [PlusTiC](https://minecraft.curseforge.com/projects/plustic))_, TwkCon throws an NPE and crashes on start.

[Crash Log](https://gist.github.com/ElvenChaos/ed5bdfd1df59137edabfe33bc5cffec9)
[TwkCon Config](https://gist.github.com/ElvenChaos/5b575dbd3e9a9a5f8c31fbae9f2a4f84)
Offending Config Line: `diamatine_actadd_plustic:d:d:d:3:d:d:d:d:d:d`

_Note: While I do have multiple entries in the relevant config, I did previously narrow down the crashing material to diamatine before posting._

Issue on PlusTiC repository: https://github.com/Landmaster/PlusTiC/issues/154

**Comment by RCXcrafter** [comment]
fixed in version 1.1.1
should be available soon

**Comment by ElvenChaos** [comment]
Thank you for the quick fix!
