### ISSUE TITLE
Crash when removing wood as a material

### ISSUE THREAD

**Issue by Shadowless99** [RCXcrafter/TweakersConstruct#10]
Hello, love your mod, but when I try to remove wood tools, the game crashes on startup.
It works flawlessly on other materials, like obsidian and stone

https://paste.dimdev.org/ateriwisuq.mccrash

thank you

**Comment by RCXcrafter** [comment]
I can't seem to reproduce this crash with just tweakers, tinkers and mantle, can you try removing some of your mods to see which one is causing it?

**Comment by Shadowless99** [comment]
Thx for the quick reply, I was able to filter it down to PlusTic. 

https://www.curseforge.com/minecraft/mc-mods/plustic

**Comment by RCXcrafter** [comment]
Landmaster has fixed the issue on their end, I'm not sure when the version of plustic will be released but that should fix it.

**Comment by Shadowless99** [comment]
Thank you
