### ISSUE TITLE
Attack Damage softcap?

### ISSUE THREAD

**Issue by edenhack** [RCXcrafter/TweakersConstruct#12]
I have a custom modpack with TAIGA,Metallurgy,base/modern metals installed for progression. I have noticed going through and tweaking stats on gear that for some reason weapons do not want to go beyond 150 damage easily. What do i mean by easily exactly? Well i have weapons with the stats tweaked to 10k damage, that show statistically as 10k damage when in mainhand. However the ticon dps text only shows a maximum attack of 150ish. Is this something on ticon's end or is tweakers construct not fully implementing the changes at large stats like that? I tried a variety of parts and such to make sure it wasnt a part incompatibility but I am unable to get past 150 range.

**Comment by RCXcrafter** [comment]
As far as I know tweakers constuct should be able to handle large numbers like that so I assume tinker's construct wasn't designed to handle such ridiculously large numbers. That being said, why would you need to set the stats so high? Do you have orespawn installed or something?

**Comment by edenhack** [comment]
Mining level is fine. But I had ice and fire turned to be sorta like raid bosses with a lot of health. Sadly tinkers doesn't seem to like those numbers for damage. Its acting like there is a soft cap around 150 where a humongous about of damage needs to be on the weapon to get any sorta gain on tinkers dps demarcation to the weapon.Sent from my Sprint Samsung Galaxy Note9.

**Comment by edenhack** [comment]
Sorry I forgot to close this, It's definitely on TiC end, he has a hardcoded softcap for every weapon. I just compiled my own version without the softcaps and everything works fine now.
