### ISSUE TITLE
MaterialCost Tweak doesn't work for Construct's Armory parts

### ISSUE THREAD

**Issue by paulgb434** [RCXcrafter/TweakersConstruct#15]
The MaterialCost tweak doesn't seem to be work with Construct's Armory parts as the material cost remains as it was before in-game. The syntax seems to be correct: "conarm:armor_trim:2", so I'm assuming that the parts are not recognized as tool parts...

**Comment by RCXcrafter** [comment]
Huh, appearently they don't extend the ToolPart class. Should be easy to fix.
