### ISSUE TITLE
Setting "Miningspeed Nerf" to 100 still applies the default Nerf (75)

### ISSUE THREAD

**Issue by Insane96** [RCXcrafter/TweakersConstruct#21]
This is the config: https://gist.github.com/Insane96/cb7af8aee5a73989e153c65049ba465a

E.g. With the config above wood has 1.5 Mining Speed while with the mod removed has 2.0

I have Tconstruct, ConArmory and Tinker Tool Levelling installed

**Comment by Eclairius** [comment]
I had a similar issue, albeit with attack damage, I found a fix for my problem, so in case it's revelant to you case I will share it:
1 - Copy your tweakersconstruct config somewhere (the next steps will end up deleting massive parts of it, so having a backup is highly recommended).
2 - Put the desired Nerfs values (attack, mining speed, etc.).
3- Set "Fill defaults" to true.
4 - Launch your game; It will generate stats tweaks for every material, with the values corresponding to bases stats with the nerfs values applied.
5 - Tweaks the stats to your liking.
