### ISSUE TITLE
Can't modify Metallurgy's Prometheum

### ISSUE THREAD

**Issue by Gebcrafter** [RCXcrafter/TweakersConstruct#26]
I have modified metallurgy 4's carmot to have lightweight and well-established successfully
```
carmot:head:established
carmot:handle:lightweight
carmot:extra:established
```
However, doing the same to prometheum does not work
```
prometheum:head:crude
prometheum:extra:crude
prometheum:handle:crude
```
I have verified not only that the material is referred to as 'prometheum' internally, but also that the trait is referred to as 'crude' internally. 
[Modlist](https://pastebin.com/Fn1nH8eH)

**Comment by RCXcrafter** [comment]
You'll have to use crude1 (or crude2) because crude is a trait with levels. I'm pretty sure all traits with levels require numbers.
