### ISSUE TITLE
[1.12.2] Cannot emboss Materials if their default traits were changed.

### ISSUE THREAD

**Issue by SonicX8000** [RCXcrafter/TweakersConstruct#30]
Minecraft: 1.12.2
Forge: 14.23.5.2854

Mods: 4
jei_1.12.2-4.15.0.291
Mantle-1.12-1.3.3.55
TConstruct-1.12.2-2.13.0.183
tweakersconstruct-1.12.2-1.5.3

=====

If you change the traits from their defaults, you won't be able to emboss tools with the altered material. I'm using the default config but removed 'paper' from the "Removed materials" section since paper has some altered traits by default. Here's an image showing you what happens when you attempt to emboss.

![](https://cdn.discordapp.com/attachments/377171551155650560/711408364231458826/changedtraitembossoddity.PNG)

Top:
I can create/change the tool with the altered 'paper' traits.

Middle:
I cannot emboss 'paper' with the altered traits as nothing appears in the output.

Bottom:
I can emboss other materials such as 'bone' since their traits are the default & unchanged.

**Comment by RCXcrafter** [comment]
this was fixed with https://github.com/RCXcrafter/TweakersConstruct/commit/94446c6631badcfc1c17c7853d7d0d2c2cb04e9b
