### ISSUE TITLE
Cant add established trait to another material

### ISSUE THREAD

**Issue by Mock17** [RCXcrafter/TweakersConstruct#32]
I tried to change Atlarus (from metallurgy 4) to have the well-established trait, i used crafttweaker and both the material and the trait id are correct, but it doesn't seem to work.

` atlarus:all:established
`

tried adding another trait to the atlarus, it worked.
also tried adding established to iron and didnt work. 

EDIT: 
it seems that removing the trait from copper removes the trait from other parts as well

**Comment by RCXcrafter** [comment]
This should be fixed in tweakers construct version 1.5.5
