### ISSUE TITLE
Cannot write read default traits back

### ISSUE THREAD

**Issue by Normal69** [RCXcrafter/TweakersConstruct#34]
Good news everyone!
I could report this issue with some more information on the topic.

Using your mod for 1.12.2 MC version.

I've used your settings to load default values from the game - which is a great idea and worked perfectly.
B:"Fill Defaults Traits"=true
B:"Fill Defaults"=true

It perfectly worked like this:
fierymetal:head:twilit,autosmelt,superheat,flammable
fierymetal:projectile:twilit,flammable
fierymetal:handle:twilit,flammable
fierymetal:extra:twilit,flammable
fierymetal🙇twilit,flammable
fierymetal:shaft:twilit,flammable

Then I've removed some materials, and moved around the traits and values.
Now, several materials are missing their traits, the values are correct.

Looking into the logs I saw several traits giving error like this:
[21:39:15] [Client thread/WARN] [tweakersconstruct]: [Trait Tweaks] Could not find trait: flammable, skipping.
So the trait value your mod has read from the game is not recognised when writing it back.

The problem appears with different several traits from Twilightforest, Construct Armory, et cetera.
I just append the part from the logfile, hope it helps: https://pastebin.com/NQ7CQB3G
The original config after running the load default options: https://pastebin.com/p0Lyye8p
My modified config which throws the log problems: https://pastebin.com/WpwHxWgJ

Also notify me if I can provide more data to help you to discover the cause!
I would like to have this fine mod made perfect. :)

**Comment by RCXcrafter** [comment]
This should be fixed in tweakers construct version 1.5.5, if not, please tell me and I'll reopen this issue.
