### ISSUE TITLE
Disable traits on slime tools

### ISSUE THREAD

**Issue by SheroxGG** [RCXcrafter/TweakersConstruct#36]
Id like to remove Bouncy trait from slime boots, but as they do not have a specified id I am not sure of what to write under here:

    # Here you can change the traits of materials for certain parts or all parts.
    # The syntax is: MaterialID:Parts:Trait1,Trait2,etc.
    # To keep all existing traits add ":false" at the end [default: [paper:all:tasty], [paper:head:cheap], [paper:handle:autosmelt], [paper:extra:holy,hellish], [paper:bow:coldblooded], [paper:bowstring:crude], [paper:projectile:dense], [paper:shaft:heavy], [paper:fletching:alien]]
    S:"Trait tweaks" <
     >

What should I type? Thanks!
![image](https://user-images.githubusercontent.com/34599826/105638100-347f3780-5e71-11eb-8289-55ab003300d3.png)

**Comment by RCXcrafter** [comment]
If you mean the slime boots you can craft, those don't have traits, you can't make them not bouncy.
If you mean construct's armory boots made of slime, you have to remove the bouncy trait from the slime material. The trait tweaks work by removing all traits from a certain part and adding the ones defined in the config. So to remove a trait you have to add all the traits it normally has except the one you want to remove.
The material IDs for slime and blue slime are "slime" and "blueslime".
to remove this trait from these materials you have to add the following to the trait tweaks:
slime:core:slimey_green_armor
blueslime:core:slimey_blue_armor

**Comment by SheroxGG** [comment]
Thanks!!! I really appreciate your help!!

**Comment by SheroxGG** [comment]
Hello! I want to disable more stuff, But I have no idea of how you know de id's from the items, do you mind showing me so I dont have to ask here everytime? I want to disable knighslime, but when I try to see the id of that item it just shows tconstruct:ingot. So how cna I find the ID to remove it? Thanks!

**Comment by RCXcrafter** [comment]
You don't need the item ID, you need the material ID which you can find in the nbt data of a part made of the material. Personally I use crafttweaker and use /ct hand on a part to see the nbt data but there are probably other mods for it too.

**Comment by SheroxGG** [comment]
Hello! Sorry for reopening! Do you mind please giving me the id that I should write? I have tried with this but it is not working >.<
![image](https://user-images.githubusercontent.com/34599826/107265419-86fd4e00-6a44-11eb-9d0f-ffdec5e692fc.png)

**Comment by SheroxGG** [comment]
Kinghtslime ones are not working. Slimes tweaks are fine

**Comment by RCXcrafter** [comment]
That looks right, what exactly are you trying to do?

**Comment by SheroxGG** [comment]
Removing Invigorating from knight slime armors

**Comment by RCXcrafter** [comment]
You're doing the opposite here, what you've put in the config is adding invigorating to knightslime. You can remove traits by adding everything except for the traits you want to remove.

**Comment by SheroxGG** [comment]
Thanks a lot!

**Comment by SheroxGG** [comment]
Hello! Sorry for reopening, but for some reason it is not working properly. I added knightslime to this list, to remove the trait that adds extra health. But for some reason it is not working properly, any idea? Thanks!
    S:"Trait tweaks" <
	slime:core:slimey_green_armor
	blueslime:core:slimey_blue_armor
	knightslime:plates:steady_armor
	knightslime:trim:steady_armor

**Comment by RCXcrafter** [comment]
you're removing it from the plates and trim part but not the core part

**Comment by SheroxGG** [comment]
the core does not have that

**Comment by SheroxGG** [comment]
![image](https://user-images.githubusercontent.com/34599826/110224294-81c3df80-7eda-11eb-9186-8b810eb4475e.png)

**Comment by RCXcrafter** [comment]
I'm not sure why it's not working for you, I copied it into my config and it worked for me.

**Comment by SheroxGG** [comment]
Its so weird :(
Slime traits are working fine, any idea of what I should do?

**Comment by SheroxGG** [comment]
Hello! I still need help, hope you can help.

**Comment by RCXcrafter** [comment]
I'm sorry but I don't know why it's not working for you.

**Comment by SheroxGG** [comment]
Could it be that armors that were made before the tweak keep the perk?

**Comment by RCXcrafter** [comment]
Yes existing gear will only update its stats when modified or repaired but the book should update automatically.

**Comment by SheroxGG** [comment]
Hello! I was wondering if there is any option to disable, a full modifier, over 50 armor pieces has Rough on it, and Id like to disable it completly. Thanks!
