### ISSUE TITLE
Adding traits disables Embossment

### ISSUE THREAD

**Issue by mistaboom** [RCXcrafter/TweakersConstruct#37]
With the default configuration file, the mod runs fine. As soon as you tell the mod to generate the tweak list for traits, the next time you boot up Minecraft, you cannot apply embossments in a tool forge. To troubleshoot I put together a mod pack including only tinker's construct, JEI, and constructs armory with tweakers Construct. Still had the issue.

**Comment by RCXcrafter** [comment]
Looks like I have to register the traits before the embossment recipes are generated.

**Comment by mistaboom** [comment]
I would be happy to assist in testing or in any way I can. Just let me know.

**Comment by mistaboom** [comment]
Duplicate of #30 
This seems like the same issue I was having. Sorry for posting a duplicate.
