### ISSUE TITLE
[1.5.6]Material additions cannot be used

### ISSUE THREAD

**Issue by Gan-N** [RCXcrafter/TweakersConstruct#38]
# Metadata: The metadata of the item (optional). [default: [stone:1:144:minecraft:bedrock:0]]
    S:"Material Additions" <
        stone:1:144:minecraft:bedrock:0
    >
When I fill in the default value, the change doesn't take effect.

**Comment by RCXcrafter** [comment]
Can you tell me what exactly isn't working? From what I can see it's working.

**Comment by Gan-N** [comment]
> Can you tell me what exactly isn't working? From what I can see it's working.

Sorry, I misunderstood the function.
I want to make it minecraft:bedrock : 0 melting to liquid:stone What should we do?

**Comment by Gan-N** [comment]
> Can you tell me what exactly isn't working? From what I can see it's working.

I didn't find it< minecraft:bedrock : 0 > melt to< liquid:stone >I hope you can support it.

**Comment by RCXcrafter** [comment]
I don't aim to support adding recipes with tweakers construct. Modtweaker already has good support for that so I recommend you try that.
