### ISSUE TITLE
"Part Creation" setting does not appear to have any effect

### ISSUE THREAD

**Issue by thailyn** [RCXcrafter/TweakersConstruct#40]
I am trying to use the "Part Creation" setting to disable some materials in the part builder, but any changes to the config file do not appear to have any effect.  My current value for the setting in the config file is

```
    S:"Part Creation" <
       paper:false:false
       wyvern_plustic:false:false
       awakened_plustic:false:false
     >
```

(where the paper part is just to test using a Vanilla, non-PlusTiC material and make sure those being unusual materials is not the cause).  I am still able to craft weapon and armor parts in the Part Builder with each of these materials.  I don't see any messages in the log saying the entry has incorrect syntax.  I'm testing this in a slightly-modified version of the Enigmatica 2 Expert modpack.

From a brief examination of the code (I am not a Minecraft mod developer, but I am a programmer), it looks like the `PartCreationTweaks.java` file was based off of the `TraitTweaks.java` file, but not all parts were sufficiently changed (e.g., class identifier in the log message is "Trait Tweaks", and the class is subscribing to the `onTraitRegister` even, instead of perhaps the `onMaterialRegistered` event).  I am not familiar with how to edit and recompile a mod locally in order to test my theory.

(Thank you for creating this mod!  It makes it trivial to modify material properties en-mass, and I hope to use it for more tweaking!)

**Comment by RCXcrafter** [comment]
Whoops, I probably should have paid a little more attention when I copied that over. The name of the method does not actually matter though, only the arguments do, which is why it worked for me when I tried setting both values to true. I probably should have tested it more thoroughly than that though.
