### ISSUE TITLE
Changing costs of tools works...sometimes.

### ISSUE THREAD

**Issue by delet3r** [RCXcrafter/TweakersConstruct#7]
```
S:"Toolpart Cost" <
        tconstruct:pick_head:3
        tconstruct:axe_head:3
        tconstruct:pan_head:4
tconstruct:sharpening_kit:4
tconstruct:sword_blade:18
tconstruct:large_sword_blade:27
tconstruct:cast:6
tconstruct:sign_head:27
tconstruct:knife_blade:27
     >
```

This is what ive added to your config file.  I first just adjusted the numbers on the three example defaults and it worked, and I added 'cast' and it worked fine.  So i added sharpening kit and the sword blades.  now the sword blades both work, but the sharpening kit is still 2, and the cast is back to 2 ingots.  What is puzzling is that it worked when i first tried it.   Am I doing somethign wrong?

**Comment by RCXcrafter** [comment]
What exactly changed when you added tconstruct:cast:6 ? As far as I know it shouldn't do anything since the cast is no toolpart. I will investigate why the sharpening kit isn't working.

**Comment by delet3r** [comment]
maybe I was mistaken, i was sure that when I first tried, it made it so i had to use 6 ingots to pour a cast.  I didnt think about the fact that they are not a true tool 'part'.  

mod is still awesome, thanks for making it.  :)

**Comment by RCXcrafter** [comment]
Forgot to close this, the cost of sharpening kits can be changed in the current version.
